// Self-hosted Shape/F5 cookie farmer + broker for the Target module.
//
// WHY THIS EXISTS: target.com is protected by Shape (F5). To log in / add-to-cart, the Go engine
// must attach a set of Shape-signed request headers (x-gyjwza5z-a/a0/b/c/d/f/z + sec-ch-ua* +
// user-agent). Those headers are generated by Shape's JS running in a REAL browser, and they are
// IP-bound — the engine replays each cookie from the exact proxy it was harvested on
// (t.SetProxy(t.ShapeProxy)). The reference implementation shipped a licensed harvester for this; this is our own,
// license-free replacement so every user farms their own cookies.
//
// TWO PARTS IN ONE PROCESS:
//   1. Broker  — HTTP server on 127.0.0.1:4727 that the engine polls. Endpoints mirror the reference implementation's:
//        GET  /cookie?type=login|atc&wait=1&timeout=ms   -> { ok, cookie: { headers, proxy } }
//        POST /saveCookies  { type, headers, proxy }      -> inject a cookie (authenticated in-app)
//        POST /demand       { activeTasks, standbyTasks, atcPerTask, basis }
//                                                          -> update live per-task bank targets
//        POST /session-ready                              -> unlock staggered ATC farming after login
//        GET  /status                                     -> pool sizes
//        (GET /proxies is gone — it returned the pool, credentials and all, to any local caller)
//   2. Farmer — Playwright browser-pool workers that drive Target through each proxy, capture the signed
//        headers off a real request, and push them into the pool.
//
// STATUS: the broker is exact and complete. The farmer's capture is a best-effort v1 — Shape is
// specifically built to resist header reuse, so the trigger/capture almost certainly needs live
// tuning against Target's current Shape build (run headful, watch which request carries the
// x-gyjwza5z-* headers, adjust). The broker means you can validate the whole chain immediately by
// POSTing one manually-harvested cookie to /saveCookies with x-zyn-token when the app supplied one.

import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { chromium as playwrightChromium } from 'playwright';
import {
  ensureProfileDir,
  harvestSourceForEngine,
  loadHarvestChromium,
  normalizeHarvesterEngine,
  workerProfileDir,
} from './shape-harvester-engine.mjs';
import { concealHarvestWindow } from './shape-harvest-window.mjs';
import { makePersona, personaInitScript, makeContextOptions, createHuman } from './harvest-persona.mjs';
import { createHarvestCoordinator } from './shape-harvest-coordinator.mjs';
import { createBankDemand } from './shape-bank-demand.mjs';
import {
  classifyHarvestPageEvidence, classifyHarvestFailure, createHarvestHealth, pickWeightedSource,
} from './shape-harvest-health.mjs';
import {
  detectShapeBrowsers, distributeShapeWorkerBrowsers, shapeBrowserLaunchOptions,
  normalizeShapeBrowserSelection, shapeBrowserSchedulerSlotCount,
} from './shape-browser-pool.mjs';
import { createShapeBrowserOptimizer } from './shape-browser-optimizer.mjs';
import { randomLoadsForBrowser, shapeFarmerThroughputOptions } from './shape-farmer-throughput.mjs';
import { createShapeWorkerScaler } from './shape-worker-scaler.mjs';
import { shapeWorkerRelaunchDelayMs } from './shape-worker-retry.mjs';
import { dismissTargetHealthDataConsent } from './target-consent-overlay.mjs';
import { runTargetAtcV2Flow, TARGET_ATC_V2_SOURCE } from './target-atc-v2.mjs';
import {
  blockHeavyResourcesEnabled, createPageBandwidthMeter, emptyBandwidthSample,
  installHeavyResourceBlock,
} from './shape-bandwidth.mjs';

// Broker port. Read from the env the app sets (ZYN_SHAPE_PORT) so the app, this farmer, and the
// Go engine cannot drift apart — three hardcoded copies is how the engine ended up dialling a port
// nobody was listening on. The literal is only the standalone-run default.
const PORT = Number(process.env.ZYN_SHAPE_PORT) || 4727;
const HOST = '127.0.0.1';
const MAX_FARMER_WORKERS = 100;
// Per-launch secret from the app, shared with the engine through its environment. Empty when the
// farmer is run standalone (no app), in which case /cookie stays open exactly as before rather than
// becoming unusable — a bare farmer has no engine to authenticate anyway.
const TOKEN = process.env.ZYN_SHAPE_TOKEN || '';
function tokenOk(req) {
  if (!TOKEN) return true;
  const sent = Buffer.from(String(req.headers['x-zyn-token'] || ''), 'utf8');
  const want = Buffer.from(TOKEN, 'utf8');
  return sent.length === want.length && crypto.timingSafeEqual(sent, want);
}

const argOf = (name, def = '') => {
  const p = process.argv.find(a => a.startsWith(`--${name}=`));
  return p ? p.slice(name.length + 3) : def;
};
const log = (...a) => console.log('[shape]', ...a);
const PRODUCER_MODE = argOf('producer', 'false') === 'true';
const HARVESTER_ID = String(argOf('harvesterId', 'legacy')).replace(/[^a-z0-9_-]/gi, '').slice(0, 64) || 'legacy';
const HARVEST_ENGINE = normalizeHarvesterEngine(argOf('engine', 'playwright'));
const PATCHRIGHT = HARVEST_ENGINE === 'patchright';
const PROFILE_ROOT = argOf('profileRoot', '') || path.join(os.tmpdir(), 'zyn-shape-patchright', HARVESTER_ID);
let chromium = playwrightChromium;
const HARVESTER_NAME = String(argOf('harvesterName', 'Cookie Harvester')).slice(0, 80);
const HARVESTER_TYPE = ['login', 'atc', 'auto'].includes(argOf('harvesterType', 'auto'))
  ? argOf('harvesterType', 'auto') : 'auto';
const HARVESTER_ATC_MODE = argOf('atcMode', 'v1').toLowerCase() === 'v2' ? 'v2' : 'v1';
const ROUTE_LABEL = String(argOf('routeLabel', 'Local')).slice(0, 100);

// ── proxy list ───────────────────────────────────────────────────────────────────
// One "host:port" or "host:port:user:pass" per line, from --proxyFile=<path>.
function loadProxies() {
  const file = argOf('proxyFile');
  if (!file || !fs.existsSync(file)) return [];
  const raw = fs.readFileSync(file, 'utf8');
  // Shred it immediately. This is the only plaintext copy of an in-house pool on the user's machine,
  // and it is needed exactly once — this call, at module load. Leaving it on disk for the lifetime of
  // the farmer (or, as before, forever) hands every credential to anyone who opens the temp folder.
  // The path is also visible in this process's command line, so the file must not outlive the read.
  try { fs.unlinkSync(file); } catch {}
  return raw.split(/\r?\n/).map(s => s.trim()).filter(Boolean)
    .map(line => {
      let source = '';
      let payload = line;
      const tab = line.indexOf('\t');
      if (tab >= 0) {
        source = line.slice(0, tab).trim();
        payload = line.slice(tab + 1).trim();
      }
      const p = payload.split(':');
      if (p.length < 2) return null;
      return {
        raw: payload,
        source,
        server: `http://${p[0]}:${p[1]}`,
        username: p[2] || '',
        password: p[3] || '',
      };
    }).filter(Boolean);
}

// ── cookie pool ────────────────────────────────────────────────────────────────────
// Each cookie: { headers: {10 required keys}, proxy: "host:port:user:pass", at: ms }
const pool = { login: [], atc: [] };
const waiters = { login: [], atc: [] };
// Process-lifetime flow counters make an empty pool intelligible. A fresh cookie may be handed
// directly to a waiting engine request and therefore never appear in `pool`; without these counters
// the UI reports zero while farming and checkout consumption are both working normally.
const activity = {
  startedAt: Date.now(),
  produced: { login: 0, atc: 0 },
  delivered: { login: 0, atc: 0 },
};
const emptyTransferTotals = () => ({
  attempts: 0,
  measuredAttempts: 0,
  unmeasuredAttempts: 0,
  cookies: 0,
  downloadBytes: 0,
  uploadBytes: 0,
  totalBytes: 0,
  proxyBytes: 0,
  directBytes: 0,
  proxyDownloadBytes: 0,
  proxyUploadBytes: 0,
  directDownloadBytes: 0,
  directUploadBytes: 0,
  proxyCookies: 0,
  directCookies: 0,
  requests: 0,
  blockedRequests: 0,
  cachedRequests: 0,
  failedRequests: 0,
  proxyRequests: 0,
  directRequests: 0,
  proxyBlockedRequests: 0,
  directBlockedRequests: 0,
  proxyCachedRequests: 0,
  directCachedRequests: 0,
  proxyFailedRequests: 0,
  directFailedRequests: 0,
});
const bandwidthActivity = {
  startedAt: activity.startedAt,
  ...emptyTransferTotals(),
  byType: { login: emptyTransferTotals(), atc: emptyTransferTotals() },
};
function addTransferSample(target, sample, cookies, proxied) {
  const downloadBytes = Math.max(0, Number(sample && sample.downloadBytes) || 0);
  const uploadBytes = Math.max(0, Number(sample && sample.uploadBytes) || 0);
  const totalBytes = downloadBytes + uploadBytes;
  target.attempts += 1;
  target.measuredAttempts += sample && sample.supported === true ? 1 : 0;
  target.unmeasuredAttempts += sample && sample.supported === true ? 0 : 1;
  target.cookies += Math.max(0, Number(cookies) || 0);
  target.downloadBytes += downloadBytes;
  target.uploadBytes += uploadBytes;
  target.totalBytes += totalBytes;
  target.proxyBytes += proxied ? totalBytes : 0;
  target.directBytes += proxied ? 0 : totalBytes;
  target.proxyDownloadBytes += proxied ? downloadBytes : 0;
  target.proxyUploadBytes += proxied ? uploadBytes : 0;
  target.directDownloadBytes += proxied ? 0 : downloadBytes;
  target.directUploadBytes += proxied ? 0 : uploadBytes;
  target.proxyCookies += proxied ? Math.max(0, Number(cookies) || 0) : 0;
  target.directCookies += proxied ? 0 : Math.max(0, Number(cookies) || 0);
  for (const field of ['requests', 'blockedRequests', 'cachedRequests', 'failedRequests']) {
    target[field] += Math.max(0, Number(sample && sample[field]) || 0);
  }
  const routePrefix = proxied ? 'proxy' : 'direct';
  target[`${routePrefix}Requests`] += Math.max(0, Number(sample && sample.requests) || 0);
  target[`${routePrefix}BlockedRequests`] += Math.max(0, Number(sample && sample.blockedRequests) || 0);
  target[`${routePrefix}CachedRequests`] += Math.max(0, Number(sample && sample.cachedRequests) || 0);
  target[`${routePrefix}FailedRequests`] += Math.max(0, Number(sample && sample.failedRequests) || 0);
}
function recordTransferSample(type, sample, cookies, proxied) {
  const measured = sample || emptyBandwidthSample(false);
  addTransferSample(bandwidthActivity, measured, cookies, proxied);
  if (bandwidthActivity.byType[type]) addTransferSample(bandwidthActivity.byType[type], measured, cookies, proxied);
}
function bandwidthStatusPayload() {
  return {
    ...bandwidthActivity,
    supported: bandwidthActivity.measuredAttempts > 0 || bandwidthActivity.attempts === 0,
    available: bandwidthActivity.measuredAttempts > 0,
    uploadEstimated: true,
    measurement: 'chromium-cdp',
    byType: {
      login: { ...bandwidthActivity.byType.login },
      atc: { ...bandwidthActivity.byType.atc },
    },
  };
}
// Producer processes do not own the bank. They mirror the broker's counts so their existing
// demand/cap coordinator can avoid farming past a shared ceiling while every producer feeds the
// same broker on :4727.
const producerBank = { login: 0, atc: 0 };
const producerWaiters = { login: 0, atc: 0 };
const producerStatusById = new Map();
let producerLastSuccessAt = 0;
// Soft bank target per type. Workers harvest until the bank reaches this depth, then close their
// browsers and relaunch only as cookies expire or the engine waits — saves proxy GB versus keeping
// idle browser/proxy sessions open or farming continuously without a cap.
// 0 = uncapped (TTL-only prune; max bandwidth). Default 50 is deep enough for drops while not
// burning proxies topping up past 70 forever on a 10-minute TTL.
const LEGACY_TARGET_POOL = parseInt(argOf('poolSize', '50'), 10);
const bankDemand = createBankDemand({ legacyPool: LEGACY_TARGET_POOL });
const initialDemand = bankDemand.snapshot();
// A producer does not own the bank and must not speculate from a stale CLI cap while the broker is
// still starting. Park both lanes until its first /status response supplies the authoritative target.
let runtimeTargets = PRODUCER_MODE ? { login: 0, atc: 0 } : initialDemand.targets;
let runtimeDemand = PRODUCER_MODE
  ? { ...initialDemand.demand, targets: { ...runtimeTargets } }
  : initialDemand.demand;
// Abort image/media only (never scripts) so Shape still runs but PDPs cost far less proxy GB.
const BLOCK_HEAVY_RESOURCES = blockHeavyResourcesEnabled(argOf('blockHeavyResources', 'true'));
const ALLOWED = argOf('types', 'login,atc').toLowerCase().split(',').map(s => s.trim()).filter(Boolean);
const SESSION_READY_AT_START = argOf('sessionReady', 'false') === 'true';
const WORKER_STAGGER_MS = parseInt(argOf('workerStaggerMs', '2000'), 10);
const INTERVAL_DELAY_MS = Math.max(0, parseInt(argOf('intervalDelayMs', '0'), 10) || 0);
const harvestCoordinator = createHarvestCoordinator({
  allowedTypes: ALLOWED,
  targetPool: LEGACY_TARGET_POOL,
  targetPools: runtimeTargets,
  sessionReady: SESSION_READY_AT_START,
  loginConcurrency: 1,
  continuousLogin: PRODUCER_MODE && HARVESTER_TYPE === 'login',
  workerStaggerMs: WORKER_STAGGER_MS,
});
function setRuntimeTargets(nextTargets) {
  const coordination = harvestCoordinator.setTargets(nextTargets);
  runtimeTargets = coordination.targets;
  return runtimeTargets;
}
const harvestHealth = createHarvestHealth();
let startedWorkerCount = 0;
let farmerBrowser = { key: 'chromium', channel: 'chromium', mode: 'not-started' };
let farmerBrowsers = [];
let workerBrowsers = [];
let workerScaler = null;
let browserOptimizer = null;

// Shape headers are short-lived; anything older is dropped by prune() rather than handed to the
// engine (a stale replay is a guaranteed 401, and it burns the task's attempt).
//
// THROUGHPUT REALITY: a bank of N with a TTL of T needs a sustained N/T harvests to hold level.
// At ~40 s per harvest, one worker produces ~1.5/min — so a 30-cookie bank on a 4-minute TTL needs
// roughly 8 workers just to stay full. Raise poolSize and workers together, or the bank silently
// settles wherever throughput caps it.
// Default raised from 4 minutes to 10. This is OUR retention window, not Target's — we cannot see
// when Shape actually stops honouring a header, so the number is a bet either way. Too low throws
// away cookies that would still have worked and wastes the harvest that produced them; too high
// replays dead ones, and each of those is a 401 that also burns the task's attempt. Overridable in
// Settings → Cookie TTL so it can be tuned against real 401 rates instead of rebuilt.
const COOKIE_TTL_MS = parseInt(argOf('cookieTtlMs', String(10 * 60 * 1000)), 10);
const {
  capturesPerLoad: CAPTURES_PER_LOAD,
  loadsPerBrowser: LOADS_PER_BROWSER,
} = shapeFarmerThroughputOptions({
  capturesPerLoad: argOf('capturesPerLoad', '1'),
  loadsPerBrowser: argOf('loadsPerBrowser', '3'),
});

// What a cookie MUST carry to be worth banking.
//
// x-gyjwza5z-a0 is deliberately NOT here. Target's current Shape build stopped emitting it —
// every observed signature is [a,b,c,d,f,z] — so requiring it meant the farmer and the browser
// extension rejected every single capture and the pool could never fill. The engine now omits
// empty headers rather than sending them blank, so a cookie without a0 replays as a browser
// without a0 does.
//
// If a0 comes back, OPTIONAL picks it up automatically and it is replayed like the rest; it just
// no longer gates the capture.
const REQUIRED = [
  'sec-ch-ua-platform', 'sec-ch-ua', 'user-agent',
  'x-gyjwza5z-a', 'x-gyjwza5z-b',
  'x-gyjwza5z-c', 'x-gyjwza5z-d', 'x-gyjwza5z-f', 'x-gyjwza5z-z',
];
const OPTIONAL = ['x-gyjwza5z-a0'];
const CAPTURED = [...REQUIRED, ...OPTIONAL];
const hasAllShapeHeaders = (h) => REQUIRED.every(k => h[k] && String(h[k]).trim() !== '');

function prune(type) {
  const now = Date.now();
  pool[type] = pool[type].filter(c => {
    const expiresAt = Number(c && c.expiresAt) || ((Number(c && c.at) || 0) + COOKIE_TTL_MS);
    return expiresAt > now;
  });
}

// ── the bank, mirrored to disk ───────────────────────────────────────────────────────
//
// The pool is process memory, and stopping tasks kills this process with taskkill /F /T — a hard
// kill, so no exit handler can ever flush it. Stop right after a pre-farm and the whole bank went
// with it: the broker that replaces this process starts empty and the UI honestly reports 0.
// Mirroring every change means the replacement reloads what was already earned.
//
// This is a buffer, not a savings account. Entries still expire on COOKIE_TTL_MS, so a quick
// stop/start returns nearly all of them and a long break correctly returns none — a restored cookie
// past its TTL is a guaranteed 401 that also burns the task's attempt.
//
// Safe to reload because each record keeps the proxy it was farmed on: Shape cookies are IP-bound
// and the engine replays them through that same line.
const BANK_FILE = argOf('bankFile', '');
let saveTimer = null;

function saveBank() {
  if (!BANK_FILE || saveTimer) return;   // coalesce — workers pool in quick bursts
  saveTimer = setTimeout(() => {
    saveTimer = null;
    try {
      prune('login'); prune('atc');
      const tmp = `${BANK_FILE}.tmp`;
      fs.writeFileSync(tmp, JSON.stringify({ savedAt: Date.now(), pool }));
      fs.renameSync(tmp, BANK_FILE);     // atomic: a half-written bank must never be loadable
    } catch (e) { log(`bank save failed: ${e.message}`); }
  }, 1000);
  if (saveTimer.unref) saveTimer.unref();  // a pending save must not hold the process open
}

function loadBank() {
  if (!BANK_FILE) return;
  try {
    if (!fs.existsSync(BANK_FILE)) return;
    const raw = JSON.parse(fs.readFileSync(BANK_FILE, 'utf8'));
    let dropped = 0;
    for (const type of ['login', 'atc']) {
      const list = Array.isArray(raw && raw.pool && raw.pool[type]) ? raw.pool[type] : [];
      // Rebuild rather than trust the file: a record with no timestamp would never prune, and one
      // with no headers would be handed to the engine as a working cookie.
      pool[type] = list.filter(c => c && c.headers && typeof c.at === 'number' && hasAllShapeHeaders(c.headers));
      const before = pool[type].length;
      prune(type);
      dropped += before - pool[type].length;
    }
    log(`bank restored: login=${pool.login.length} atc=${pool.atc.length}`
      + (dropped ? ` (${dropped} expired on load)` : ''));
  } catch (e) { log(`bank load failed: ${e.message}`); }
}

function pushCookie(type, headers, proxy, options = {}) {
  if (!pool[type]) return false;
  const norm = {};
  for (const k of Object.keys(headers || {})) norm[k.toLowerCase()] = headers[k];
  if (!hasAllShapeHeaders(norm)) return false;
  if (type === 'login') harvestCoordinator.noteLoginHarvested();
  const now = Date.now();
  const requestedExpiry = Number(options.expiresAt) || 0;
  const cookie = {
    type,
    headers: norm,
    proxy: proxy || '',
    at: now,
    expiresAt: requestedExpiry > now ? requestedExpiry : now + COOKIE_TTL_MS,
    harvesterId: String(options.harvesterId || HARVESTER_ID || '').slice(0, 64),
    source: String(options.source || 'inBot').slice(0, 32),
  };
  if (PRODUCER_MODE) {
    activity.produced[type]++;
    producerBank[type]++;
    producerLastSuccessAt = now;
    submitCookieToBroker(type, cookie);
    return true;
  }
  activity.produced[type]++;
  const w = waiters[type].shift();
  if (w) {
    activity.delivered[type]++;
    clearTimeout(w.timer);
    w.resolve(cookie);
  }   // hand straight to a waiting request
  else pool[type].push(cookie);
  log(`pooled ${type} cookie (pool: login=${pool.login.length} atc=${pool.atc.length})`);
  saveBank();
  return true;
}

function takeCookie(type, waitMs) {
  return new Promise((resolve) => {
    prune(type);
    const c = pool[type].shift();
    if (c) {
      activity.delivered[type]++;
      saveBank();
      resolve(c);
      return;
    }   // spent — don't hand it back after a restart
    if (!waitMs) { resolve(null); return; }
    const entry = { resolve: null, timer: null };
    entry.resolve = resolve;
    entry.timer = setTimeout(() => {
      const i = waiters[type].indexOf(entry);
      if (i >= 0) waiters[type].splice(i, 1);
      resolve(null);
    }, Math.min(waitMs, 30000));
    waiters[type].push(entry);
  });
}

function brokerRequest(method, requestPath, payload, callback, attempt = 0) {
  const body = payload == null ? '' : JSON.stringify(payload);
  const req = http.request({
    host: HOST,
    port: PORT,
    path: requestPath,
    method,
    timeout: 2500,
    headers: {
      ...(TOKEN ? { 'x-zyn-token': TOKEN } : {}),
      ...(body ? { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body) } : {}),
    },
  }, (res) => {
    let response = '';
    res.on('data', chunk => { response += chunk; });
    res.on('end', () => {
      let parsed = null;
      try { parsed = JSON.parse(response || '{}'); } catch {}
      if (res.statusCode >= 200 && res.statusCode < 300) {
        if (callback) callback(null, parsed);
        return;
      }
      if (callback) callback(new Error(`broker returned ${res.statusCode}`));
    });
  });
  req.on('error', (error) => {
    if (attempt < 2) {
      setTimeout(() => brokerRequest(method, requestPath, payload, callback, attempt + 1), 400 * (attempt + 1));
      return;
    }
    if (callback) callback(error);
  });
  req.on('timeout', () => req.destroy(new Error('broker request timed out')));
  if (body) req.write(body);
  req.end();
}

function submitCookieToBroker(type, cookie) {
  brokerRequest('POST', '/saveCookies', {
    type,
    headers: cookie.headers,
    proxy: cookie.proxy,
    expiresAt: cookie.expiresAt,
    harvesterId: HARVESTER_ID,
    source: cookie.source,
  }, (error, response) => {
    if (error) {
      producerBank[type] = Math.max(0, producerBank[type] - 1);
      log(`harvester ${HARVESTER_NAME}: broker submission failed — ${error.message}`);
    } else if (!response || !response.saved) {
      producerBank[type] = Math.max(0, producerBank[type] - 1);
    }
  });
}

function refreshProducerBank() {
  if (!PRODUCER_MODE) return;
  brokerRequest('GET', '/status', null, (error, status) => {
    const pauseUntilAuthoritativeDemand = () => {
      producerWaiters.login = 0;
      producerWaiters.atc = 0;
      setRuntimeTargets({ login: 0, atc: 0 });
      runtimeDemand = {
        ...runtimeDemand, basis: 'paused', effectiveTasks: 0, targets: { ...runtimeTargets },
      };
    };
    // Producers do not own demand. Stay fail-closed before the parent publishes its first
    // per-task target and whenever the broker becomes unreachable; otherwise a stale high target
    // can burn proxies in a harvest/failed-submit loop during broker recovery.
    if (error || !status || !status.pools || status.demand?.mode !== 'per-task') {
      pauseUntilAuthoritativeDemand();
      return;
    }
    producerBank.login = Math.max(0, Number(status.pools.login) || 0);
    producerBank.atc = Math.max(0, Number(status.pools.atc) || 0);
    producerWaiters.login = Math.max(0, Number(status.activity?.waiting?.login) || 0);
    producerWaiters.atc = Math.max(0, Number(status.activity?.waiting?.atc) || 0);
    const brokerTargets = status.demand.targets || status.targets;
    if (!brokerTargets || typeof brokerTargets !== 'object') {
      pauseUntilAuthoritativeDemand();
      return;
    }
    setRuntimeTargets(brokerTargets);
    runtimeDemand = { ...status.demand, targets: { ...runtimeTargets } };
  });
}

function producerStatusPayload() {
  const scale = workerScaler && workerScaler.snapshot();
  const health = harvestHealth.snapshot();
  return {
    id: HARVESTER_ID,
    name: HARVESTER_NAME,
    type: HARVESTER_TYPE,
    atcMode: HARVESTER_ATC_MODE,
    route: ROUTE_LABEL,
    browser: BROWSER_SELECTION,
    configuredWorkers: startedWorkerCount,
    activeWorkers: scale ? scale.activeWorkers : 0,
    produced: { ...activity.produced },
    failures: health.failures || {},
    quarantinedProxies: Number(health.quarantinedProxies) || 0,
    bandwidth: bandwidthStatusPayload(),
    browserPerformance: browserOptimizer ? browserOptimizer.snapshot() : null,
    lastSuccessAt: producerLastSuccessAt,
    startedAt: activity.startedAt,
    demand: { ...runtimeDemand, targets: { ...runtimeTargets } },
    targets: { ...runtimeTargets },
  };
}

function publishProducerStatus() {
  if (!PRODUCER_MODE) return;
  brokerRequest('POST', '/harvesterStatus', producerStatusPayload(), () => {});
}

// ── broker HTTP server ──────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  const u = new URL(req.url, `http://${HOST}:${PORT}`);
  const json = (obj, code = 200) => { res.writeHead(code, { 'content-type': 'application/json' }); res.end(JSON.stringify(obj)); };

  if (req.method === 'GET' && u.pathname === '/cookie') {
    // Every cookie is returned with the proxy it was farmed on, so an open /cookie leaks a live pool
    // credential per call. Only the engine consumes this, and the engine is our own child — it gets
    // the token in its environment. /status stays open on purpose: it carries no secret (pid and
    // counts), and the app probes it to identify an orphaned broker before reclaiming the port, which
    // happens across launches when the token has already been regenerated. External browser clients
    // go through the main-process compatibility bridge, which adds the per-launch token without
    // exposing it to Chrome.
    if (!tokenOk(req)) { json({ ok: false, error: 'unauthorized' }, 401); return; }
    const type = (u.searchParams.get('type') || 'login').toLowerCase();
    const wait = u.searchParams.get('wait') === '1';
    const timeout = parseInt(u.searchParams.get('timeout') || '0', 10);
    takeCookie(type === 'atc' ? 'atc' : 'login', wait ? timeout : 0).then(cookie => {
      if (!cookie) { json({ ok: false, cookie: { headers: {}, proxy: '' } }); return; }
      json({ ok: true, cookie: {
        type: cookie.type || type,
        source: cookie.source || 'inBot',
        headers: cookie.headers,
        proxy: cookie.proxy,
        expiresAt: cookie.expiresAt,
        harvesterId: cookie.harvesterId || '',
      } });
    });
    return;
  }
  if (req.method === 'POST' && u.pathname === '/demand') {
    // Demand controls how much proxy-backed work every producer performs, so only the parent app
    // may mutate it. Producers learn the canonical targets from /status and never choose their own.
    if (!tokenOk(req)) { json({ ok: false, error: 'unauthorized' }, 401); return; }
    let body = '';
    req.on('data', chunk => { body += chunk; if (body.length > 64000) req.destroy(); });
    req.on('end', () => {
      try {
        const next = bankDemand.apply(JSON.parse(body || '{}'));
        runtimeDemand = next.demand;
        setRuntimeTargets(next.targets);
        log(`bank demand: basis=${runtimeDemand.basis} active=${runtimeDemand.activeTasks}`
          + ` standby=${runtimeDemand.standbyTasks} effective=${runtimeDemand.effectiveTasks}`
          + ` targets login=${runtimeTargets.login} atc=${runtimeTargets.atc}`);
        json({ ok: true, demand: { ...runtimeDemand, targets: { ...runtimeTargets } } });
      } catch (error) { json({ ok: false, error: error.message }, 400); }
    });
    return;
  }
  if (req.method === 'POST' && u.pathname === '/saveCookies') {
    if (!tokenOk(req)) { json({ ok: false, error: 'unauthorized' }, 401); return; }
    let body = '';
    req.on('data', d => { body += d; if (body.length > 1e6) req.destroy(); });
    req.on('end', () => {
      try {
        const data = JSON.parse(body || '{}');
        const items = Array.isArray(data) ? data : [data];
        let n = 0;
        for (const it of items) {
          const type = (it.type || 'login').toLowerCase() === 'atc' ? 'atc' : 'login';
          prune(type);
          if (!bankDemand.accepts(type, pool[type].length, waiters[type].length > 0)) continue;
          if (pushCookie(type, it.headers || {}, it.proxy || '', {
            expiresAt: Number(it.expiresAt) || 0,
            harvesterId: it.harvesterId,
            source: it.source,
          })) n++;
        }
        json({ ok: true, saved: n });
      } catch (e) { json({ ok: false, error: e.message }, 400); }
    });
    return;
  }
  if (req.method === 'POST' && u.pathname === '/harvesterStatus') {
    if (!tokenOk(req)) { json({ ok: false, error: 'unauthorized' }, 401); return; }
    let body = '';
    req.on('data', chunk => { body += chunk; if (body.length > 256000) req.destroy(); });
    req.on('end', () => {
      try {
        const data = JSON.parse(body || '{}');
        const id = String(data.id || '').replace(/[^a-z0-9_-]/gi, '').slice(0, 64);
        if (!id) { json({ ok: false, error: 'missing harvester id' }, 400); return; }
        producerStatusById.set(id, { ...data, id, seenAt: Date.now() });
        json({ ok: true });
      } catch (error) { json({ ok: false, error: error.message }, 400); }
    });
    return;
  }
  if (req.method === 'POST' && u.pathname === '/session-ready') {
    // Only the app may unlock the ATC workers. It sends this after the engine emits account-cookie
    // and that session has been persisted; accepting an unauthenticated local request here would let
    // any process bypass the cold-login safety gate.
    if (!tokenOk(req)) { json({ ok: false, error: 'unauthorized' }, 401); return; }
    const changed = harvestCoordinator.markSessionReady();
    if (changed) log(`account session saved — unlocking ATC workers (${WORKER_STAGGER_MS}ms stagger)`);
    json({ ok: true, changed, sessionReady: true });
    return;
  }
  if (req.method === 'GET' && u.pathname === '/status') {
    prune('login'); prune('atc');
    const coordination = harvestCoordinator.state();
    const health = harvestHealth.snapshot();
    const rawScale = workerScaler ? workerScaler.snapshot() : {
      policy: 'fixed', desiredWorkers: 0,
      activeWorkers: 0, configuredCeiling: startedWorkerCount, hardLimit: startedWorkerCount,
      recentSamples: 0, recentErrors: 0, recentErrorRate: 0,
      decisionSamples: 0, decisionErrors: 0, decisionErrorRate: 0,
      distinctPressureSources: 0, requiredDistinctPressureSources: 0,
      scaleDowns: 0, lastDownscale: null,
      recovery: {
        active: false, eligibleInMs: 0, successes: 0, distinctHealthySources: 0,
        requiredSuccesses: 0, requiredDistinctSources: 0, scaleUps: 0, lastUpscale: null,
      },
      scheduling: {
        slotCount: 0, activeWorkerIds: [], activeBrowserCounts: {}, browserActivations: {},
        rotations: 0, rotationEvery: 2, activeLeaseCompletions: {}, lastRotation: null,
      },
    };
    const browserPerformance = browserOptimizer ? browserOptimizer.snapshot() : null;
    const optimizerActiveCounts = Object.fromEntries((browserPerformance?.browsers || [])
      .map(browser => [browser.key, browser.activeWorkers]));
    const scale = browserPerformance ? {
      ...rawScale,
      scheduling: { ...rawScale.scheduling, activeBrowserCounts: optimizerActiveCounts },
    } : rawScale;
    const performanceByBrowser = new Map((browserPerformance?.browsers || [])
      .map(browser => [browser.key, browser]));
    const activeWorkerIds = new Set(scale.scheduling && scale.scheduling.activeWorkerIds || []);
    const browsers = farmerBrowsers.map(browser => ({
      ...browser,
      configuredWorkers: workerBrowsers.filter(candidate => candidate.key === browser.key).length,
      activeWorkers: performanceByBrowser.has(browser.key)
        ? performanceByBrowser.get(browser.key).activeWorkers
        : workerBrowsers.filter((candidate, id) =>
          activeWorkerIds.has(id) && candidate.key === browser.key).length,
      performance: performanceByBrowser.get(browser.key) || null,
    }));
    // `app` and `owner` let the app identify this process positively before ever reclaiming the
    // port from it — image-name matching would be reckless (node.exe is everyone's dev server).
    const now = Date.now();
    const harvesters = [...producerStatusById.values()]
      .filter(item => now - (Number(item.seenAt) || 0) < 30000)
      .map(item => ({ ...item }));
    const producerWorkers = harvesters.reduce((sum, item) => sum + (Number(item.activeWorkers) || 0), 0);
    const producerConfigured = harvesters.reduce((sum, item) => sum + (Number(item.configuredWorkers) || 0), 0);
    const demandStatus = bankDemand.snapshot();
    json({ ok: true, app: 'zyn-shape-broker', pid: process.pid,
           owner: Number(process.env.ZYN_OWNER_PID) || 0,
           pools: { login: pool.login.length, atc: pool.atc.length }, proxies: PROXIES.length,
           demand: demandStatus.demand, targets: demandStatus.targets,
           harvesters,
           activity: {
             startedAt: activity.startedAt,
             produced: { ...activity.produced },
             delivered: { ...activity.delivered },
             waiting: { login: waiters.login.length, atc: waiters.atc.length },
           },
           sessionReady: coordination.sessionReady, inFlight: coordination.inFlight,
           health: { ...health, activeWorkers: scale.activeWorkers + producerWorkers,
             busyWorkers: coordination.inFlight.login + coordination.inFlight.atc,
             configuredWorkers: startedWorkerCount + producerConfigured,
             browserOptimization: browserPerformance,
             scaling: producerConfigured ? {
               ...scale,
               desiredWorkers: producerConfigured,
               hardLimit: producerConfigured,
               activeWorkers: producerWorkers,
             } : scale,
             browser: farmerBrowser, browsers } });
    return;
  }
  // GET /proxies used to return PROXIES.map(p => p.raw) — every line of the in-house pool, complete
  // with username and password, to anyone who could reach the port. Nothing ever called it; a repo-wide
  // search found only this route and its own doc comment. It was the cheapest possible way to lift the
  // whole pool: one curl, no key, no unpacking. Removed outright rather than gated — an endpoint whose
  // entire job is to hand out credentials has no safe form.
  json({ ok: true }); // '/' and anything else
});

// ── farmer ───────────────────────────────────────────────────────────────────────────
const PROXIES = loadProxies();

// Pick a proxy at RANDOM from the whole list, not by walking it.
//
// Every worker used to step through the list one index at a time starting at its own id, so with
// three workers they crawled the same prefix in lockstep — 0,1,2,3… / 1,2,3,4… / 2,3,4,5… — hitting
// the same session within seconds of each other and never getting past the first couple of hundred
// entries of a 20,000-entry list however long the farm ran.
//
// `recent` stops naive random from undoing that: a uniform draw would still land on a
// just-used session now and then, and reusing an exit IP within a few minutes is exactly the
// pattern that gets a session queued or blocked. Shared across workers, so two of them cannot draw
// the same session at once. It is a ring, not a permanent exclusion — a session becomes eligible
// again once RECENT_MAX others have been used, which for any real pool is a long time.
const RECENT_MAX = Math.min(500, Math.max(1, Math.floor(PROXIES.length / 2)));
const recent = new Set();
const recentOrder = [];
const sourceScores = Object.create(null);
function recordSourceResult(source, ok) {
  const name = String(source || '').trim();
  if (!name) return;
  const current = sourceScores[name] || { ok: 0, fail: 0 };
  if (ok) current.ok += 1;
  else current.fail += 1;
  sourceScores[name] = current;
}
function pickProxy() {
  if (!PROXIES.length) return { proxy: null, waitMs: 0 };
  const healthy = [];
  for (let i = 0; i < PROXIES.length; i++) {
    if (harvestHealth.isProxyAvailable(PROXIES[i].raw)) healthy.push(i);
  }
  if (!healthy.length) {
    return { proxy: null, waitMs: harvestHealth.nextProxyReadyMs(PROXIES.map(proxy => proxy.raw)) || 1000 };
  }
  const sources = [...new Set(healthy.map(idx => PROXIES[idx].source).filter(Boolean))];
  const preferred = sources.length > 1 ? pickWeightedSource(sources, sourceScores) : '';
  const inSource = preferred ? healthy.filter(idx => PROXIES[idx].source === preferred) : healthy;
  const pool = inSource.length ? inSource : healthy;
  const fresh = pool.filter(idx => !recent.has(idx));
  const choices = fresh.length ? fresh : pool;
  const idx = choices[Math.floor(Math.random() * choices.length)];
  recent.add(idx);
  recentOrder.push(idx);
  while (recentOrder.length > RECENT_MAX) recent.delete(recentOrder.shift());
  return { proxy: PROXIES[idx], waitMs: 0 };
}
const HEADLESS = PATCHRIGHT ? false : argOf('headless', 'false') === 'true';
const BROWSER_SELECTION = normalizeShapeBrowserSelection(argOf('browsers', 'auto'));
// Every browser in the pool has an explicit channel. In headless mode that opts Chrome, Edge, and
// bundled Chromium into their regular browser's New Headless implementation.
// Park the harvest windows off-screen instead of on top of whatever the operator is doing. Defaults
// ON; pass --offscreen=false to watch a harvest live while tuning selectors.
const OFFSCREEN = argOf('offscreen', 'true') !== 'false';
// ATC cookies are harvested by actually clicking add-to-cart, which needs a product that is IN
// STOCK. The task's own TCIN is exactly the wrong choice for a drop — it's out of stock until the
// moment it isn't, so the button never appears and no cart_items request ever fires. Harvest from
// stable in-stock items instead; the Shape signature is scoped to the endpoint, not to the product.
//
// A LIST is rotated rather than hammering one page: repeatedly carting the same item from one IP
// looks like exactly what it is, and if a single item goes out of stock mid-drop a one-item config
// would silently stop producing ATC cookies at the worst possible moment.
const ATC_TCIN = argOf('atcTcin', '') || argOf('tcin', '');
const ATC_TARGETS = (argOf('atcTcins', '') || ATC_TCIN)
  .split(',').map(s => s.trim()).filter(Boolean);
let atcIdx = 0;

// Accepts bare TCINs or full URLs, so a product link pasted straight from Target works as-is.
function nextAtcUrl() {
  if (!ATC_TARGETS.length) return 'https://www.target.com/c/top-deals';
  const t = ATC_TARGETS[atcIdx++ % ATC_TARGETS.length];
  return /^https?:\/\//i.test(t) ? t : `https://www.target.com/p/-/A-${t}`;
}
const DIAG = argOf('diag', 'false') === 'true';   // verbose per-step logging for tuning
const ACCT_EMAIL = process.env.SHAPE_ACCT_EMAIL || '';   // real account, for a matching-context login
const ACCT_PASS = process.env.SHAPE_ACCT_PASS || '';
const LOGIN_MODE = argOf('loginMode', 'password');       // 'otp' (Get a code) | 'password' (Enter your password)

// Which request to harvest — matched to the reference implementation's own harvester extension (their src/background.js
// intercepts exactly these via CDP Fetch and stubs the response so Target never gets the real call):
//   login       -> gsp.target.com/.../username_validations   (the email-check step; its Shape
//                  signature is session-level and covers the whole auth flow — works for BOTH
//                  password and OTP login, so the engine replays it on credential_validations /
//                  secure_codes. A random email is fine; no real account/password/OTP needed here.)
//   add-to-cart -> carts.target.com/web_checkouts/v1/cart_items
// Shape headers are validated against the request they were signed for, so we must harvest the
// EXACT endpoint the engine replays them on:
//   login + OTP mode      -> secure_codes_unidentified  (engine: request.go LoginOTP)
//   login + password mode -> username_validations       (email-check step)
//   add-to-cart           -> cart_items
function harvestUrlRe(type) {
  if (type === 'atc') return /carts\.target\.com\/web_checkouts\/v1\/cart_items/i;
  if (LOGIN_MODE === 'otp') return /gsp\.target\.com\/gsp\/authentications\/v1\/secure_codes_unidentified/i;
  return /gsp\.target\.com\/gsp\/authentications\/v1\/username_validations/i;
}
function contextMatch(type, url) { return harvestUrlRe(type).test(url); }

function launchOptionsFor(proxy, selectedBrowser) {
  // Strip Playwright's automation tells so Shape doesn't fingerprint the browser as a bot and bake
  // that signal into the header signature (which Target then 401s on replay).
  const args = ['--no-sandbox', '--disable-setuid-sandbox', '--disable-blink-features=AutomationControlled', '--disable-features=IsolateOrigins,site-per-process'];
  // Get the harvest windows out of the operator's face WITHOUT going headless — headless is exactly
  // the signal the persona work exists to avoid. Parking them far off-screen keeps a real compositor,
  // real paint and a real GPU process; the window simply isn't on any monitor. Windows then reports
  // the window as occluded, and Chromium's response to that is to throttle timers, freeze rAF and
  // background the renderer — which would stall Shape's own VM and produce short signatures. The
  // three --disable flags switch that throttling off, so an off-screen harvest runs at the same speed
  // as a visible one. None of them are observable from page JS.
  if (!HEADLESS && OFFSCREEN) {
    args.push('--disable-backgrounding-occluded-windows', '--disable-renderer-backgrounding', '--disable-background-timer-throttling');
    if (process.platform !== 'darwin') args.push('--window-position=-32000,-32000');
  }
  const launchOptions = shapeBrowserLaunchOptions(selectedBrowser, {
    headless: HEADLESS, args, ignoreDefaultArgs: ['--enable-automation'],
  });
  if (proxy) {
    launchOptions.proxy = { server: proxy.server };
    if (proxy.username && proxy.password) { launchOptions.proxy.username = proxy.username; launchOptions.proxy.password = proxy.password; }
  }
  return launchOptions;
}

// Capture up to CAPTURES_PER_LOAD distinct signed requests from one fresh page/context. `reuse` is
// owned by the worker session; without it this function preserves its original standalone behavior
// and launches/closes a browser itself.
async function harvestOnce(type, proxy, selectedBrowser, reuse = null) {
  const persistent = PATCHRIGHT && reuse && typeof reuse.newContext !== 'function';
  const persona = makePersona();
  const browser = reuse || await chromium.launch(launchOptionsFor(proxy, selectedBrowser));
  let context = null;
  let page = null;
  let bandwidthMeter = null;
  try {
    if (persistent) {
      context = reuse;
      page = await context.newPage();
      await concealHarvestWindow(page, { offscreen: OFFSCREEN });
      page.on('load', () => { concealHarvestWindow(page, { offscreen: OFFSCREEN }).catch(() => {}); });
    } else {
      // Browser reuse does not mean Target-state reuse. Every load gets a fresh context, storage jar,
      // page, and persona while retaining the expensive browser process and its fixed proxy.
      context = await browser.newContext(makeContextOptions(persona));
      page = await context.newPage();
    }
    const interceptedEndpoint = harvestUrlRe(type);
    bandwidthMeter = await createPageBandwidthMeter(context, page, {
      isLocalResponse: request => {
        const url = String(request && request.url || '');
        const method = String(request && request.method || '').toUpperCase();
        const resourceType = String(request && request.resourceType || '').toLowerCase();
        if (/^(?:data|blob|about|file):/i.test(url)) return true;
        if (interceptedEndpoint.test(url) && method !== 'OPTIONS' && resourceType !== 'document') return true;
        return type === 'atc' && HARVESTER_ATC_MODE === 'v2' && resourceType === 'document'
          && /^https:\/\/(?:www\.)?target\.com\/p\//i.test(url);
      },
    });
    // Bandwidth: drop product images/media through the proxy. Scripts/CSS/XHR stay so Shape and
    // Add-to-Cart keep working. Disable with --blockHeavyResources=false if yield ever dips.
    await installHeavyResourceBlock(page, {
      enabled: BLOCK_HEAVY_RESOURCES,
      onBlocked: request => bandwidthMeter.noteBlocked(request),
    });
    if (!persistent) await page.addInitScript(personaInitScript(persona)).catch(() => {});
    const human = createHuman(page, persona);

    // Stealth + device persona are installed above via personaInitScript(), before any navigation.
    // Everything the old inline block did is covered there, and driven by ONE coherent persona
    // rather than a second set of independently-random values that could contradict it.

    // Why a harvest failed, filled in by the ATC branch and reported alongside the screenshot.
    let blockedPage = false;
    let queuedOut = false;   // still in Target's waiting room when the budget ran out
    let atcNote = '';
    // ATC has direct page evidence, so preserve its category instead of later reverse-engineering
    // one from a human-readable note. Empty means the generic classifier still owns the outcome.
    let failureCategory = '';
    // The Shape headers actually seen on the harvest request. If the target endpoint fires but the
    // signature is short, THAT is the failure — not the click, not the proxy — and without this the
    // log said "no cart_items request fired" while the request had plainly gone out.
    let bestSig = null;

    // Target's virtual waiting room: a near-blank page reading "Sorry for the wait — It's a little
    // busier than we expected." It is NOT a block — it is a queue, and the right response to a queue
    // is to stay in it. Leaving and re-navigating forfeits your place.
    //
    // Without this the harvest waited 8s, found no add-to-cart button, and reported "button never
    // appeared" — indistinguishable from a broken page, and it gave up exactly when patience was the
    // one thing that would have worked. Matched on the wording rather than any hashed class name.
    const QUEUE_RE = /sorry for the wait|busier than we expected/i;
    const inQueue = async () => {
      try { return QUEUE_RE.test(await page.title() + ' ' + (await page.locator('body').innerText({ timeout: 1500 }))); }
      catch { return false; }
    };
    // Resolves true once the queue clears, false if it outlasts `ms`.
    const waitOutQueue = async (ms) => {
      if (!(await inQueue())) return true;
      log(`  in Target's waiting room — holding position (up to ${Math.round(ms / 1000)}s)`);
      const deadline = Date.now() + ms;
      while (Date.now() < deadline) {
        await page.waitForTimeout(2500);
        if (!(await inQueue())) {
          log('  ✓ through the waiting room');
          return true;
        }
      }
      return false;
    };

    // Click by SELECTOR, resolved at click time. An ElementHandle captured earlier goes stale the
    // moment the page re-renders, and a stale handle fails permanently instead of finding the new
    // node — which is what "Element is not attached to the DOM" meant all over the harvest logs.
    const clickNow = async (sel, timeout = 4000) => {
      try { await page.click(sel, { timeout }); return true; } catch { return false; }
    };

    const captured = await new Promise((resolve) => {
      let done = false;
      const bag = [];
      const capturedKeys = new Set();
      let resolveFirstHeaders;
      const firstHeadersPromise = new Promise(firstResolve => { resolveFirstHeaders = firstResolve; });
      const finish = () => { if (!done) { done = true; resolve(bag.length ? bag : null); } };
      const deadline = setTimeout(finish, 90000);   // proxies are slow — be patient

      // Every POST the page makes during a harvest. When clicks land but no cart_items request
      // ever fires, the interesting question is where add-to-cart went instead — this turns that
      // from a guess into a list.
      const postedUrls = new Set();
      page.on('request', (r) => {
        if (r.method() === 'POST' || r.method() === 'PUT') postedUrls.add(r.url().split('?')[0]);
      });

      const seenSigned = new Set();
      page.on('request', async (r) => {
        try {
          const h = await r.allHeaders();
          const shapeKeys = Object.keys(h).filter(k => k.startsWith('x-gyjwza5z-')).map(k => k.replace('x-gyjwza5z-', '')).sort();
          if (shapeKeys.length && DIAG) {
            const u = r.url().slice(0, 60);
            if (!seenSigned.has(u)) { seenSigned.add(u); log(`  ↳ signed[${shapeKeys.join(',')}]: ${r.method()} ${u}`); }
          }
        } catch {}
      });

      // Endpoint whose Shape headers the engine will replay. We INTERCEPT and ABORT it: Shape headers
      // carry a single-use nonce, so if the browser's own request went through, the nonce would be
      // spent and the engine's replay would be a rejected duplicate (401 Shape Block). Aborting keeps
      // the nonce fresh for the engine's first-and-only use.
      const routeRe = harvestUrlRe(type);
      // Stub response mirrors the reference implementation's: login → fake 400 ("bad request"), atc → fake 201 ("created").
      // The page PARSES these. An empty {} throws inside Target's own JS, which leaves the sheet in
      // a broken state — and we then click the same page another six or seven times expecting it to
      // work. Return something shaped like the real thing so the page settles and stays clickable.
      const stub = type === 'atc'
        ? {
            status: 201,
            contentType: 'application/json',
            headers: { 'access-control-allow-origin': 'https://www.target.com', 'access-control-allow-credentials': 'true' },
            body: JSON.stringify({
              cart_id: 'stub-' + Math.random().toString(36).slice(2, 12),
              cart_type: 'REGULAR',
              cart_state: 'PENDING',
              cart_items: [],
              summary: { item_count: 1, cart_subtotal: 0, grand_total: 0 },
            }),
          }
        : {
            status: 400,
            contentType: 'application/json',
            headers: { 'access-control-allow-origin': 'https://www.target.com', 'access-control-allow-credentials': 'true' },
            // The shape Target's own client expects for "no such account" — it renders a normal
            // inline error rather than blowing up on an unparseable body.
            body: JSON.stringify({
              errors: [{ errorKey: '_ERR_USER_DOES_NOT_EXIST', errorMessage: "We can't find your account." }],
            }),
          };

      (async () => {
        try {
          await page.route(routeRe, async (route) => {
            const req = route.request();
            // Let CORS preflights (OPTIONS) and navigations through; only the real POST carries the
            // Shape headers and the single-use nonce.
            if (done || req.method() === 'OPTIONS' || req.resourceType() === 'document') { try { await route.continue(); } catch {} return; }
            try {
              const h = await req.allHeaders();
              if (hasAllShapeHeaders(h)) {
                const picked = {};
                for (const k of CAPTURED) if (h[k]) picked[k] = h[k];
                // Only bank distinct signatures. If Target repeats a nonce/header set after the
                // stubbed response, replaying that duplicate twice would guarantee one rejection.
                const captureKey = CAPTURED.map(key => `${key}:${picked[key] || ''}`).join('\n');
                if (!capturedKeys.has(captureKey)) {
                  capturedKeys.add(captureKey);
                  bag.push(picked);
                  resolveFirstHeaders(picked);
                }
                if (DIAG) log(`  ✓ captured ${bag.length}/${CAPTURES_PER_LOAD} ${req.method()} ${req.url().slice(0, 50)} (stubbed — nonce fresh)`);
                if (bag.length >= CAPTURES_PER_LOAD && !(type === 'atc' && HARVESTER_ATC_MODE === 'v2')) {
                  clearTimeout(deadline);
                  finish();
                }
                // Stub the response so Target NEVER receives the real request → nonce stays unused for
                // the engine's first-and-only replay (exactly what the reference implementation's extension does).
                bandwidthMeter.noteLocalResponse(req);
                try { await route.fulfill(stub); } catch { try { await route.abort(); } catch {} }
                return;
              }
              // Incomplete signature (Shape often omits a0 on the first cart_items — its VM hasn't
              // finished interrogating the page yet). Stub it anyway rather than continue(): letting
              // it through spends the nonce AND really adds the item, after which the button changes
              // state and never re-fires. Stubbing keeps the page retry-able for the next click.
              const seen = Object.keys(h).filter(k => k.startsWith('x-gyjwza5z-')).map(k => k.slice(11)).sort();
              const got = seen.join(',');
              if (!bestSig || seen.length > bestSig.length) bestSig = seen;
              const short = REQUIRED.filter(k => k.startsWith('x-gyjwza5z-') && !h[k]).map(k => k.slice(11));
              // "signature" is in KEEP_IN_QUIET, so this reaches the operator instead of being
              // swallowed as debug chatter — it is the single most useful line when a harvest fails.
              log(`  incomplete signature: got [${got}], missing [${short.join(',')}] — stubbed, retrying`);
              bandwidthMeter.noteLocalResponse(req);
              try { await route.fulfill(stub); } catch { try { await route.abort(); } catch {} }
              return;
            } catch {}
            try { await route.continue(); } catch {}
          }).catch(() => {});
          if (type === 'atc' && HARVESTER_ATC_MODE === 'v2') {
            const url = nextAtcUrl();
            try {
              if (DIAG) log(`  step: Target ATC+ synthetic PDP for ${url}`);
              await runTargetAtcV2Flow({
                page,
                human,
                productLink: url,
                waitForHeaders: () => firstHeadersPromise,
              });
            } catch (error) {
              if (bestSig) failureCategory = classifyHarvestPageEvidence({ signatureObserved: true });
              atcNote = String(error && error.message || error).slice(0, 180);
              if (DIAG) log(`  step: Target ATC+ — ${atcNote}`);
            }
            return;
          }
          // Warm the homepage with mouse/scroll until PerimeterX cookies appear (a cold hit to the
          // auth page gets risk-scored and bounced to the homepage — this is why /login redirected).
          await page.goto('https://www.target.com/', { waitUntil: 'commit', timeout: 20000 }).catch(() => {});
          await page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => {});
          // Behave like someone actually looking at the page until PerimeterX issues its cookies.
          // The routine is drawn from a pool and reordered every session, so no two harvests perform
          // the same actions in the same sequence — a fixed move-then-scroll loop repeated on every
          // worker is itself a pattern worth scoring against.
          const warmDeadline = Date.now() + 18000;
          let pxSeen = false;
          let routine = [];
          while (Date.now() < warmDeadline) {
            routine = await human.warmUp(2).catch(() => routine);
            try {
              const names = (await context.cookies()).map(c => c.name);
              if (names.some(n => ['_px3', '_pxhd', 'pxcts', '_pxvid'].includes(n))) { pxSeen = true; break; }
            } catch {}
          }
          if (DIAG) log(`  step: warm done (px cookie: ${pxSeen}) — ${persona.platform} ${persona.screen.width}x${persona.screen.height}, did [${routine.join(' > ')}]`);

          if (type === 'login') {
            // The /login page redirects to the homepage through proxy IPs. /account/signup (the URL
            // target-register.mjs drives successfully through proxies) renders the same unified auth
            // form: enter email in #username, click #login ("Continue") -> Shape-signed auth POST
            // with the full header set (incl. a0). Works for existing accounts too — the first step
            // is identical for login and signup.
            await page.goto('https://www.target.com/account/signup', { waitUntil: 'commit', timeout: 20000 }).catch(() => {});
            await page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => {});
            if (DIAG) {
              await page.waitForTimeout(6000);
              try {
                const dir = path.join(os.tmpdir(), 'shape-debug'); fs.mkdirSync(dir, { recursive: true });
                const shot = path.join(dir, `login-page-${Date.now()}.png`);
                await page.screenshot({ path: shot });
                const hasUser = !!(await page.$('#username'));
                const hasPwd = !!(await page.$('#password'));
                log(`  step: at ${page.url().slice(0, 50)} | #username=${hasUser} #password=${hasPwd} | shot=${shot}`);
              } catch {}
            }
            let email = await page.waitForSelector('#username', { timeout: 30000 }).catch(() => null);
            if (!email) {
              // Fallback: click a sign-in entry point to force the real form.
              if (DIAG) log('  step: #username not found, clicking sign-in entry');
              for (const sel of ['a[href*="/login"]', '[data-test="@web/Account/AccountLink"]', 'text=Sign in']) {
                const el = await page.$(sel).catch(() => null);
                if (el) { await el.click().catch(() => {}); break; }
              }
              email = await page.waitForSelector('#username', { timeout: 15000 }).catch(() => null);
            }
            if (email) {
              // Just enter an email and click Continue — that fires username_validations, which our
              // route intercepts, captures, and stubs (400) before it reaches Target. A random email
              // is fine (Shape signs the request regardless of the email's validity); no real
              // account, password, OTP, or passkey menu needed. Mirrors the reference implementation's harvester extension.
              // In OTP mode the engine replays on secure_codes_unidentified, which only fires for a
              // REAL account (Target won't send a code to an unknown address) and only after picking
              // "Get a code" on the method menu. In password mode username_validations is enough, so
              // a random email works there.
              const useEmail = LOGIN_MODE === 'otp' && ACCT_EMAIL
                ? ACCT_EMAIL
                : 'p' + Math.random().toString(36).slice(2, 12) + '@gmail.com';
              if (DIAG) log(`  step: entering ${LOGIN_MODE === 'otp' ? 'account' : 'random'} email + Continue`);
              // Typed with a varying rhythm, thinking pauses and the occasional corrected typo, then
              // the button approached along a path — a fixed 40ms-per-key cadence followed by an
              // instant click is a keystroke signature, and this is the exact request Shape signs.
              if (!(await human.type('#username', useEmail).catch(() => false))) {
                await email.type(useEmail, { delay: 40 });
              }
              await human.wait(200 + Math.random() * 500);
              if (!(await human.click('#login').catch(() => false))) {
                const btn = await page.$('#login'); if (btn) await btn.click().catch(() => {});
              }

              if (LOGIN_MODE === 'otp') {
                // Method menu: "Use a passkey" / "Get a code" / "Enter your password". Clicking
                // "Get a code" fires secure_codes_unidentified, which our route captures and stubs
                // (so Target never actually sends a code and the nonce stays fresh for the engine).
                await page.waitForTimeout(4000);
                const codeSels = [
                  'button:has-text("Get a code")', 'text=Get a code',
                  '[data-test*="sendCode"]', 'button:has-text("Send a code")',
                ];
                const deadlineOtp = Date.now() + 25000;
                while (!done && Date.now() < deadlineOtp) {
                  for (const sel of codeSels) {
                    if (done) break;
                    // Same stale-handle trap as the add-to-cart path: the sign-in panel re-renders
                    // while we wait, so a handle grabbed a moment ago points at a node that no longer
                    // exists. Re-resolve at click time.
                    if (!(await page.$(sel).catch(() => null))) continue;
                    if (DIAG) log(`  step: choosing "${sel}" → secure_codes_unidentified`);
                    if (await clickNow(sel)) await page.waitForTimeout(3000);
                  }
                  await page.waitForTimeout(1500);
                }
                if (DIAG && !done) log('  step: otp — secure_codes never fired');
              }
            } else if (DIAG) log('  step: form never appeared');
            await page.waitForTimeout(LOGIN_MODE === 'otp' ? 4000 : 20000);
          } else {
            const url = nextAtcUrl();   // rotates through the configured in-stock harvest products
            await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45000 }).catch(() => {});
            await page.waitForTimeout(3000);
            const dismissHealthConsent = async () => {
              const consent = await dismissTargetHealthDataConsent(page);
              if (consent.dismissed) {
                if (DIAG) log('  step: dismissed Target Health Data Consent overlay');
              } else if (consent.found) {
                // "failed" survives quiet-log filtering so a Target markup change does not regress
                // back into the misleading "button present but blocked" diagnosis.
                log(`  health consent overlay dismissal failed${consent.error ? ` — ${consent.error}` : ''}`);
              }
              return consent.dismissed;
            };
            await dismissHealthConsent();
            // Clicking add-to-cart on a sign-in-gated item does not fire cart_items — it routes the
            // session into Target's unified auth page (…/login?…actions=create_session_request_username),
            // sometimes via an ATA captcha. The old failure ladder never looked at page.url(), so that
            // came out as "clicked 2x but no cart_items request fired" — a moved-endpoint story — while
            // the click loop spent its remaining ~20s clicking selectors on a login page. Read the
            // POSTs we already collect, and compare the URL against the TCIN we asked for.
            const atcTcin = (url.match(/A-(\d+)/) || [])[1] || '';
            // AtaVerifyCaptcha is NOT a challenge indicator — Target's PDP posts it routinely. Treating
            // it as one broke the click loop at 0 clicks on pages that were fine (the log showed the
            // note firing while page.url() was still the requested TCIN and the title was the real
            // product, and one such run went on to fire cart_items). It is kept only as a suffix on a
            // bounce that the URL has already proven, never as a reason to stop clicking.
            const sawCaptcha = () => [...postedUrls].some(u => /captcha/i.test(u));
            const offPdp = () => {
              const now = page.url();
              if (/\/login|\/account\/|captcha/i.test(now)) return true;
              // Target rewrites /p/-/A-123 to /p/<slug>/-/A-123, so match on the TCIN, not the path.
              // Guarded: with no TCINs configured nextAtcUrl() returns /c/top-deals, which has none.
              return !!atcTcin && !now.includes('A-' + atcTcin);
            };
            // Hold position if Target queued us, rather than reporting a missing button.
            const throughQueue = await waitOutQueue(45000);
            if (!throughQueue) {
              queuedOut = true;
            } else {
              await page.waitForTimeout(5000);
              await dismissHealthConsent();
            }
            // Target PDPs gate the real add-to-cart behind a fulfillment choice. Clicking the actual
            // "Add to cart" / "Ship it" / "Pick it up" control fires the cart_items POST our route
            // intercepts+stubs (201). Try the data-test hooks first, then fall back to button text.
            // done becomes true as soon as the route captures cart_items, so we can early-exit.
            // Reports whether the click ACTUALLY landed. The old version swallowed the failure and
            // returned true regardless, so a click that timed out was logged as "clicked" — the diag
            // output claimed three successful clicks on a page where not one of them reached the
            // button. A click timeout here almost always means an overlay is eating pointer events,
            // which is a completely different problem from "the selector is wrong", and the log said
            // nothing to tell them apart.
            // page.click() re-resolves the selector at click time and auto-waits. The previous
            // version grabbed an ElementHandle and clicked it seconds later, which on a React PDP
            // that re-renders constantly meant the node had usually been replaced — hence the
            // "Element is not attached to the DOM" failures that dominated the logs. A stale handle
            // fails permanently; re-resolving just finds the new node.
            const clickSel = async (sel) => {
              try {
                // human.click() moves along a curved path onto the element, pauses, and holds the
                // button down for a realistic moment. It falls back to page.click() internally if
                // the element has no box, so a plain click is still the floor, never the default.
                if (await human.click(sel, { timeout: 4000 })) return true;
                await page.click(sel, { timeout: 4000 });
                return true;
              } catch (e) {
                const msg = String(e.message || e).split(String.fromCharCode(10))[0];
                // "waiting for selector" just means it is absent; the caller already counts that.
                if (DIAG && !/waiting for (locator|selector)/i.test(msg)) log(`  step: click BLOCKED on ${sel} — ${msg}`);
                return false;
              }
            };
            void clickNow;   // the ATC branch wants the diagnostic, so it uses clickSel instead

            // Target's bot-block interstitial. It renders over the PDP with a backdrop that
            // intercepts pointer events, so every click times out while the page still LOOKS normal
            // underneath — the failure screenshot shows a perfectly good Add to cart button. Worth
            // naming explicitly: it means this proxy/browser was flagged, not that ATC is broken.
            const blocked = async () => {
              try {
                const t = await page.locator('text=/Something went wrong/i').first().isVisible({ timeout: 250 });
                return !!t;
              } catch { return false; }
            };
            const attempts = [
              'button[data-test="shippingButton"]',
              'button[data-test="orderPickupButton"]',
              'button[data-test="shipItButton"]',
              'button[id^="addToCart"]',
              'button[data-test="addToCartButton"]',
              'button:has-text("Add to cart")',
              'button:has-text("Ship it")',
              'button:has-text("Pick it up")',
            ];
            const clickDeadline = Date.now() + 24000;
            let clicked = 0, found = 0, wasBlocked = false;
            while (!done && Date.now() < clickDeadline) {
              // The sheet can mount after the PDP's first render or after the waiting room clears,
              // so re-probe before every click pass instead of relying on one timing-sensitive check.
              await dismissHealthConsent();
              if (await blocked()) { wasBlocked = true; break; }   // no point clicking a dead page
              if (offPdp()) break;                                 // bounced off the PDP — stop clicking a page that isn't it
              for (const sel of attempts) {
                if (done) break;
                const el = await page.$(sel).catch(() => null);
                if (!el) continue;
                found++;
                if (await clickSel(sel)) {
                  clicked++;
                  if (DIAG) log(`  step: clicked ${sel} (atc attempt ${clicked})`);
                  await page.waitForTimeout(3500);
                }
              }
              if (done) break;
              await page.waitForTimeout(1500);
            }
            if (!done) {
              // Say WHICH of the three failures this was, because the fix differs completely:
              // a block means rotate/refarm, no button means the page or selectors changed, and
              // clicks that landed but produced nothing means Target moved the endpoint.
              if (wasBlocked || await blocked()) blockedPage = true;
              // Must sit above BOTH queuedOut and !found: `found`/`clicked` are declared once outside
              // the loop and never reset, so after a bounce they still hold their pre-navigation counts
              // and the old ladder fell through to the endpoint-moved branch. Deliberately does NOT set
              // blockedPage — that flag makes line 614 and the fail string print the bot-block text and
              // throw this note away, swapping one wrong diagnosis for another.
              else if (offPdp()) {
                const now = page.url();
                failureCategory = classifyHarvestPageEvidence({ navigationFailed: /^chrome-error:/i.test(now) });
                atcNote = `bounced off the product page after ${clicked} click(s) — now on ${now.slice(0, 100)}`
                  + (/\/login/i.test(now) ? ' — Target redirected this anonymous add-to-cart attempt to sign-in' : '')
                  + (/^chrome-error:/i.test(now) ? ' — the product navigation failed' : '')
                  + (sawCaptcha() ? ' (AtaVerifyCaptcha also posted; that endpoint alone does not prove a challenge)' : '');
              }
              else if (queuedOut) {
                failureCategory = classifyHarvestPageEvidence({ queued: true });
                atcNote = "still in Target's waiting room after 45s — not a block, just busy";
              }
              else if (!found) {
                failureCategory = classifyHarvestPageEvidence();
                atcNote = 'add-to-cart button never appeared';
              }
              else if (!clicked) {
                failureCategory = classifyHarvestPageEvidence();
                atcNote = `add-to-cart controls were found ${found}x, but no click reached a control — another page layer may be intercepting pointer events`;
              }
              else if (bestSig) {
                // The request DID go out — the signature on it was just short. This is a Shape
                // problem, not a click or endpoint problem, and they need completely different fixes.
                failureCategory = classifyHarvestPageEvidence({ signatureObserved: true });
                const missing = REQUIRED.filter(k => k.startsWith('x-gyjwza5z-') && !bestSig.includes(k.slice(11))).map(k => k.slice(11));
                atcNote = `cart_items fired ${clicked}x but the signature was short — got [${bestSig.join(',')}], missing [${missing.join(',')}]`;
              } else {
                // Name the endpoints so a moved add-to-cart is visible rather than inferred.
                // doubleclick's ad beacons are target.com-adjacent, hundreds of chars long, and told us
                // nothing — one of them swallowed the whole log line. Cut them with the other trackers.
                failureCategory = classifyHarvestPageEvidence();
                const targetPosts = [...postedUrls].filter(u => /target\.com/i.test(u) && !/firefly|telemetry|collector|doubleverify|doubleclick|adservice|scorecardresearch/i.test(u));
                atcNote = `clicked ${clicked}x but no cart_items request fired`
                  + (targetPosts.length ? ` — page posted to: ${targetPosts.slice(0, 4).join(' , ')}` : ' — page posted nothing to target.com');
              }
              if (DIAG) log('  step: atc — ' + (blockedPage ? 'Target served its bot-block page' : atcNote));
            }
            await page.waitForTimeout(3000);
          }
        } catch (e) {
          // This used to be `catch {}`. Anything thrown in the login or ATC step — a navigation that
          // lost the browser, a detached frame, a timeout inside a helper — vanished here, atcNote
          // stayed empty, and the worker reported the bare fallback "no capture". That names the
          // symptom (nothing was harvested) while hiding the only thing that explains it. Record the
          // reason so it reaches the operator through the normal failure line instead.
          if (!atcNote) atcNote = `harvest step threw: ${String(e && e.message || e).split('\n')[0].slice(0, 140)}`;
        } finally {
          // A page may legitimately produce fewer signatures than requested. Return what it did
          // produce when its interaction window is over instead of waiting out the 90-second guard.
          clearTimeout(deadline);
          finish();
        }
      })();
    });

    // On failure, capture what the page actually shows so we can tell a PX block from plain latency.
    let fail = '';
    if (!captured) {
      try {
        const url = page.url();
        const title = await page.title().catch(() => '');
        const bodyText = await page.locator('body').innerText({ timeout: 1500 }).catch(() => '');
        // The ATC click loop detects this interstitial while it is working, but login can land on the
        // same page before any ATC selectors run. Inspect the final visible page so both lanes report
        // the same structured Target-block/captcha outcome.
        if (/something went wrong|access denied|request rejected/i.test(`${title} ${bodyText}`)) blockedPage = true;
        const captchaPage = /captcha|verify (that )?you are human/i.test(`${url} ${title} ${bodyText}`);
        // A Chromium network-error document does not preserve the failed tunnel code in page.url(),
        // so the earlier bounce check can only call it navigation. The rendered error text does
        // preserve it. Feed that evidence through the shared classifier so the failed managed route
        // is cooled and rotated instead of recycling a healthy browser against the same dead tunnel.
        const visibleFailureCategory = classifyHarvestFailure(`${url} ${title} ${bodyText}`);
        const proxyErrorPage = visibleFailureCategory === 'proxy';
        if (proxyErrorPage) failureCategory = 'proxy';
        else if (blockedPage) failureCategory = classifyHarvestPageEvidence({ confirmedBlock: true });
        else if (captchaPage) failureCategory = classifyHarvestPageEvidence({ confirmedCaptcha: true });
        else if (queuedOut) failureCategory = classifyHarvestPageEvidence({ queued: true });
        const dir = path.join(os.tmpdir(), 'shape-debug');
        fs.mkdirSync(dir, { recursive: true });
        const shot = path.join(dir, `fail-${type}-${Date.now()}.png`);
        await page.screenshot({ path: shot }).catch(() => {});
        const why = proxyErrorPage ? 'PROXY TUNNEL FAILED — rotating this route'
                  : blockedPage ? 'BOT-BLOCKED by Target (page says "Something went wrong")'
                  : captchaPage ? 'CAPTCHA challenge blocked the harvest'
                  : queuedOut ? "QUEUED — Target's waiting room never cleared"
                  : (atcNote || 'no capture');
        // The url/title/screenshot triple is for whoever is tuning selectors, not for someone watching
        // their tasks run — a local temp path and a page title tell an ordinary user nothing they can
        // act on. Keep the reason (which names what to do) and hide the forensics behind --diag.
        fail = DIAG ? `${why} | url=${url} | title="${title}" | shot=${shot}` : why;
      } catch (e) { fail = 'diag error: ' + e.message; }
    }
    const bandwidth = bandwidthMeter ? await bandwidthMeter.stop() : emptyBandwidthSample(false);
    return {
      headers: captured,
      fail,
      failureCategory,
      source: harvestSourceForEngine(HARVEST_ENGINE,
        type === 'atc' && HARVESTER_ATC_MODE === 'v2' ? TARGET_ATC_V2_SOURCE : 'inBot'),
      bandwidth,
    };
  } catch (error) {
    const bandwidth = bandwidthMeter
      ? await bandwidthMeter.stop().catch(() => emptyBandwidthSample(false))
      : emptyBandwidthSample(false);
    if (error && typeof error === 'object') {
      error.bandwidth = bandwidth;
      throw error;
    }
    const wrapped = new Error(String(error));
    wrapped.bandwidth = bandwidth;
    throw wrapped;
  } finally {
    if (bandwidthMeter) await bandwidthMeter.stop().catch(() => {});
    if (persistent) {
      if (page) await page.close().catch(() => {});
    } else {
      // A reused browser must not retain pages, cookies, storage, or personas between loads.
      if (context) await context.close().catch(() => {});
      if (!reuse && browser) await browser.close().catch(() => {});
    }
  }
}

// Which cookie type to harvest next. Harvesting is DEMAND-DRIVEN: a login harvest is slow (real
// account email + "Get a code" menu) and completely wasted when the account already has a saved
// session and the engine only ever asks for atc. So:
//   1. Anything the engine is actively blocked on wins outright.
//   2. Otherwise only pre-warm the types this run can actually use (ALLOWED, from --types).
//   3. Among those, keep the emptier pool topped up.
// Engine demand also re-enables a type that --types excluded — a saved session can be expired, and
// the engine will then ask for a login cookie after all.
function workerScaleSourceKey(proxy, selectedBrowser, workerId) {
  if (proxy && proxy.raw) {
    return `proxy:${crypto.createHash('sha256').update(proxy.raw).digest('hex').slice(0, 16)}`;
  }
  return `home:${selectedBrowser.key}:${workerId}`;
}

async function farmerWorker(id, initialBrowser) {
  // A worker reuses one expensive browser process for a small random number of loads. The proxy is
  // a browser launch option, so it remains fixed for that session; every load still gets a fresh
  // context/persona inside harvestOnce().
  let browser = null;
  let sessionBrowser = null;
  let sessionProxy = null;
  let loadsLeft = 0;
  let sessionLoads = 0;
  let firstSession = true;
  const endSession = async () => {
    if (browser) await browser.close().catch(() => {});
    if (sessionBrowser && browserOptimizer) browserOptimizer.release(id);
    browser = null;
    sessionBrowser = null;
    sessionProxy = null;
    loadsLeft = 0;
    sessionLoads = 0;
  };

  // Keeps the pools topped up, one browser at a time. Proxy choice is pickProxy()'s job.
  for (;;) {
    if (!workerScaler || !workerScaler.isActive(id)) {
      // A scaled-down slot must release both its browser memory and its pinned proxy immediately
      // after any in-flight harvest finishes.
      await endSession();
      await sleep(500);
      continue;
    }
    prune('login'); prune('atc');
    // reserve() increments the in-flight count before this loop reaches its first await. That is the
    // critical section: all workers may observe an empty pool, but only one can claim login.
    const reservation = harvestCoordinator.reserve({
      pools: PRODUCER_MODE ? producerBank : pool,
      waiters: PRODUCER_MODE ? producerWaiters : waiters,
      workerId: id,
      unavailableTypes: harvestHealth.coolingTypes(),
    });
    if (!reservation) {
      // Full banks, lane cooldowns, and the pre-session ATC gate can all park a worker for minutes.
      // Do not hold an idle browser/proxy pairing across that gap.
      await endSession();
      const waitMs = harvestHealth.nextCooldownMs();
      await sleep(waitMs ? Math.min(2000, Math.max(500, waitMs)) : 500);
      continue;
    }
    const type = reservation.type;
    let selectedBrowser = sessionBrowser || initialBrowser;
    let harvested = false;
    let failure = '';
    let failureCategory = '';
    let banked = 0;
    let parkedByTarget = false;
    let wasReused = false;
    let bandwidth = null;
    let proxy = sessionProxy;
    const startedAt = Date.now();
    let nextLoopDelayMs = 1000;
    try {
      if (!browser || loadsLeft <= 0) {
        await endSession();
        const proxyChoice = pickProxy();
        if (proxyChoice.waitMs) {
          // This is deliberate health backpressure, not a new failed harvest. Release the lane and
          // wait without feeding a synthetic error back into the concurrency scaler.
          await sleep(Math.min(5000, Math.max(500, proxyChoice.waitMs)));
          continue;
        } else {
          proxy = proxyChoice.proxy;
          sessionProxy = proxy;
          selectedBrowser = browserOptimizer
            ? browserOptimizer.acquire(id, firstSession ? initialBrowser.key : '')
            : initialBrowser;
          firstSession = false;
          sessionBrowser = selectedBrowser;
          browser = PATCHRIGHT
            ? await chromium.launchPersistentContext(
              ensureProfileDir(workerProfileDir(PROFILE_ROOT, HARVESTER_ID, id)),
              launchOptionsFor(proxy, selectedBrowser),
            )
            : await chromium.launch(launchOptionsFor(proxy, selectedBrowser));
          if (PATCHRIGHT) {
            const firstPage = browser.pages?.()[0];
            if (firstPage) await concealHarvestWindow(firstPage, { offscreen: OFFSCREEN });
          }
          sessionLoads = randomLoadsForBrowser(LOADS_PER_BROWSER);
          loadsLeft = sessionLoads;
        }
      } else {
        proxy = sessionProxy;
        selectedBrowser = sessionBrowser || initialBrowser;
        wasReused = true;
      }

      if (browser) {
        if (type === 'login') {
          log(`farmer worker ${id} [${selectedBrowser.key}]: reserved the single login lane`);
        }
        loadsLeft -= 1;
        const result = await harvestOnce(type, proxy, selectedBrowser, browser);
        const { headers, fail, source } = result;
        bandwidth = result.bandwidth || null;
        failureCategory = result.failureCategory || '';
        const batch = Array.isArray(headers) ? headers : headers ? [headers] : [];
        for (const captured of batch) {
          // A multi-capture page may reach a configured bank ceiling in one load. Waiting engine
          // requests still take priority; otherwise stop at the target instead of overshooting it.
          // A null target is legacy uncapped mode; dynamic zero explicitly parks prewarm.
          const bankDepth = PRODUCER_MODE ? producerBank[type] : pool[type].length;
          const waitingDepth = PRODUCER_MODE ? producerWaiters[type] : waiters[type].length;
          const target = runtimeTargets[type];
          if (target !== null && !waitingDepth && bankDepth >= target) {
            parkedByTarget = true;
            break;
          }
          if (pushCookie(type, captured, proxy ? proxy.raw : '', { source })) banked++;
        }
        harvested = banked > 0;
        if (!harvested && !parkedByTarget) {
          failure = fail || (headers ? 'captured signature could not be banked' : 'timeout');
        }
      }
    } catch (e) {
      bandwidth = e && e.bandwidth || bandwidth;
      failure = String(e && e.message || e);
    }
    finally { reservation.release({ success: harvested }); }
    recordTransferSample(type, bandwidth, banked, !!proxy);
    if (parkedByTarget && !harvested) {
      log(`farmer worker ${id} [${selectedBrowser.key}]: ${type} target changed while harvesting; parking`);
      await endSession();
      await sleep(Math.max(500, INTERVAL_DELAY_MS));
      continue;
    }
    if (harvested) {
      if (browserOptimizer) browserOptimizer.recordOutcome({
        workerId: id,
        browserKey: selectedBrowser.key,
        success: true,
        cookies: banked,
        durationMs: Date.now() - startedAt,
        bandwidth,
      });
      harvestHealth.recordSuccess({ type, proxyKey: proxy && proxy.raw });
      recordSourceResult(proxy && proxy.source, true);
      workerScaler.recordSuccess({
        sourceKey: workerScaleSourceKey(proxy, selectedBrowser, id), workerId: id,
      });
      const took = ((Date.now() - startedAt) / 1000).toFixed(1);
      log(`farmer worker ${id} [${selectedBrowser.key}]: +${banked} ${type} in ${took}s`
        + ` (${wasReused ? 'reused' : 'fresh'} browser, ${loadsLeft}/${sessionLoads} loads remain)`);
      if (loadsLeft <= 0) await endSession();
    } else {
      const category = failureCategory || classifyHarvestFailure(failure);
      if (browserOptimizer) browserOptimizer.recordOutcome({
        workerId: id,
        browserKey: selectedBrowser.key,
        success: false,
        durationMs: Date.now() - startedAt,
        bandwidth,
        failureCategory: category,
      });
      const outcome = harvestHealth.recordFailure({ type, category, proxyKey: proxy && proxy.raw });
      recordSourceResult(proxy && proxy.source, false);
      // Health telemetry needs route independence without proxy credentials. Fixed scheduling never
      // uses this evidence to deactivate a worker; quarantine owns the failed route instead.
      workerScaler.recordFailure({
        category, scope: outcome.scope, sourceKey: workerScaleSourceKey(proxy, selectedBrowser, id), workerId: id,
      });
      nextLoopDelayMs = shapeWorkerRelaunchDelayMs();
      const backpressure = outcome.scope === 'lane'
        ? `lane cooldown ${Math.ceil(outcome.cooldownMs / 1000)}s`
        : outcome.scope === 'proxy'
          ? `localized to proxy for ${Math.ceil(outcome.proxyQuarantineMs / 1000)}s`
          : 'localized to failed browser session';
      log(`farmer worker ${id} [${selectedBrowser.key}]: ${type} failure [${category}] via ${proxy ? 'proxy' : 'home IP'} — `
        + `${failure.slice(0, 220)}; ${backpressure}; fresh browser in ${(nextLoopDelayMs / 1000).toFixed(1)}s`);
      // Never reuse a session that just failed. The health layer may have quarantined its proxy,
      // and bypassing pickProxy() with the still-live browser would defeat that quarantine.
      await endSession();
    }
    await sleep(Math.max(nextLoopDelayMs, INTERVAL_DELAY_MS));
  }
}
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

// ── boot ────────────────────────────────────────────────────────────────────────────
// Before the broker accepts anything, so the first /cookie or /status sees the real level rather
// than a zero that fills in a moment later. This matters for the broker-only process too — it is
// exactly the one that replaces a killed farmer and would otherwise report an empty bank.
function startFarming(browserMode) {
  // Bank level every 20s — without this you cannot tell whether pre-farming is keeping up or
  // quietly settling below target because throughput cannot cover the TTL.
  setInterval(() => {
    if (!PRODUCER_MODE) { prune('login'); prune('atc'); }
    const health = harvestHealth.snapshot();
    const scale = workerScaler && workerScaler.snapshot();
    const optimization = browserOptimizer && browserOptimizer.snapshot();
    const cooling = Object.entries(health.cooldowns).filter(([, lane]) => lane.remainingMs > 0)
      .map(([type, lane]) => `${type}:${Math.ceil(lane.remainingMs / 1000)}s`).join(',') || 'none';
    const browserMix = optimization
      ? optimization.browsers.filter(browser => browser.activeWorkers > 0)
        .map(browser => `${browser.key}:${browser.activeWorkers}`).join(',')
      : scale ? Object.entries(scale.scheduling.activeBrowserCounts)
        .filter(([, count]) => count > 0).map(([key, count]) => `${key}:${count}`).join(',') : '';
    const browserLeader = optimization
      ? optimization.learning ? 'learning' : optimization.leader?.key || 'none'
      : '';
    const loginCap = runtimeTargets.login === null ? '' : `/${runtimeTargets.login}`;
    const atcCap = runtimeTargets.atc === null ? '' : `/${runtimeTargets.atc}`;
    const counts = PRODUCER_MODE ? producerBank : { login: pool.login.length, atc: pool.atc.length };
    log(`bank: login=${counts.login}${loginCap} atc=${counts.atc}${atcCap} (ttl ${Math.round(COOKIE_TTL_MS / 1000)}s)`
      + ` | health ok=${health.successes.total} fail=${health.failures.total}`
      + ` blocked=${health.failures.byCategory.target_block} cooldown=${cooling}`
      + ` localized=${health.backpressure.localizedFailures} quarantined=${health.quarantinedProxies}`
      + (scale ? ` workers=${scale.activeWorkers}/${scale.hardLimit} policy=${scale.policy} errors=${Math.round(scale.recentErrorRate * 100)}%`
        + ` errorSources=${scale.distinctPressureSources}`
        + `:${scale.decisionErrors}/${scale.decisionSamples}`
        + ` browsers=${browserMix || 'none'} rotations=${scale.scheduling.rotations}`
        + (optimization ? ` browserPolicy=${optimization.policy} leader=${browserLeader}` : '') : ''));
  }, 20000).unref?.();

  loadHarvestChromium(HARVEST_ENGINE).then((loaded) => {
    chromium = loaded;
    if (PATCHRIGHT) log('engine: headed persistent Chrome (experimental)');
    return detectShapeBrowsers(
    (options) => chromium.launch(options),
    (browser) => log(`browser: ${browser.key} not available on this machine — skipping`),
    BROWSER_SELECTION,
  );
  }).then((detected) => {
    if (!detected || !detected.length) {
      log(BROWSER_SELECTION === 'auto'
        ? 'browser detection failed — no Chrome, Edge, Brave, Vivaldi, Yandex, Opera, or bundled Chromium browser is available'
        : `browser detection failed — ${BROWSER_SELECTION} is not available`);
      return;
    }
    log(`browsers: ${detected.map(browser => browser.key).join(', ')} (selection: ${BROWSER_SELECTION})`);
    const requestedWorkers = parseInt(argOf('workers', ''), 10);
    const engineCap = MAX_FARMER_WORKERS;
    const configuredWorkers = Number.isFinite(requestedWorkers)
      ? Math.max(1, Math.min(requestedWorkers, engineCap)) : Math.min(detected.length, engineCap);
    // A managed Local producer intentionally allows up to its configured worker count. Legacy mode
    // remains one home-IP lane, preserving the original conservative behavior.
    const proxyCapacity = PROXIES.length || (PRODUCER_MODE ? configuredWorkers : 1);
    const hardLimit = Math.min(configuredWorkers, proxyCapacity);
    // Idle loops are cheap (they do not own a browser until active). Keep at least one schedulable
    // slot per detected channel even when the concurrency ceiling is smaller than the browser pool,
    // so the fair scheduler can rotate every proven browser through limited capacity.
    const schedulerSlots = shapeBrowserSchedulerSlotCount(detected, hardLimit);
    workerBrowsers = distributeShapeWorkerBrowsers(detected, schedulerSlots);
    browserOptimizer = createShapeBrowserOptimizer({
      browsers: detected,
      workerCount: hardLimit,
    });
    workerScaler = createShapeWorkerScaler({
      configuredWorkers,
      browserCount: detected.length,
      proxyCapacity,
      workerKeys: workerBrowsers.map(browser => browser.key),
    });
    farmerBrowsers = detected.map(browser => ({ ...browser, mode: browserMode }));
    startedWorkerCount = configuredWorkers;
    workerBrowsers.forEach((browser, id) => farmerWorker(id, browser));
    const scale = workerScaler.snapshot();
    const optimization = browserOptimizer.snapshot();
    log(`fixed worker slots ${scale.activeWorkers}/${scale.hardLimit} active immediately; scheduler `
      + `${workerBrowsers.length}: ${workerBrowsers.map(browser => browser.key).join(', ')}`
      + ` — browser policy ${optimization.policy} (${optimization.minimumSamples} comparable samples each), `
      + `no error scale-down, login concurrency 1, session ${SESSION_READY_AT_START ? 'restored' : 'pending'}`);
    publishProducerStatus();
  }).catch((error) => log(`browser detection failed: ${error.message}`));
}

if (PRODUCER_MODE) {
  const browserMode = HEADLESS ? 'new-headless' : OFFSCREEN ? 'headed/off-screen' : 'headed/visible';
  farmerBrowser = { key: 'pool', channel: '', mode: browserMode };
  log(`producer ${HARVESTER_NAME} starting (type ${HARVESTER_TYPE}, engine ${HARVEST_ENGINE}, route ${ROUTE_LABEL}, proxies ${PROXIES.length})`);
  refreshProducerBank();
  publishProducerStatus();
  setInterval(refreshProducerBank, 3000).unref?.();
  setInterval(publishProducerStatus, 3000).unref?.();
  startFarming(browserMode);
} else {
  loadBank();
  server.on('error', (e) => { log(`broker error: ${e.message}${e.code === 'EADDRINUSE' ? ` (port ${PORT} in use)` : ''}`); process.exit(1); });
  server.listen(PORT, HOST, () => {
    const browserMode = HEADLESS ? 'new-headless' : OFFSCREEN ? 'headed/off-screen' : 'headed/visible';
  const farmingDisabled = argOf('noFarm', 'false') === 'true';
  farmerBrowser = farmingDisabled
    ? { key: 'chromium', channel: 'chromium', mode: 'broker-only' }
    : { key: 'pool', channel: '', mode: browserMode };
  log(`broker listening on http://${HOST}:${PORT}  (proxies: ${PROXIES.length}, browser: ${farmerBrowser.mode}`
    + `, bank ${runtimeTargets.login === null && runtimeTargets.atc === null
      ? 'uncapped' : `soft-target login=${runtimeTargets.login} atc=${runtimeTargets.atc}`}`
    + `, heavy-resources ${BLOCK_HEAVY_RESOURCES ? 'blocked' : 'allowed'})`);
  if (farmingDisabled) { log('farmer disabled (--noFarm) — authenticated broker-only mode'); return; }
    startFarming(browserMode);
  });
}

// Never let a stray browser/page rejection take down the broker — log and keep serving. On Node 22+
// an unhandled rejection would otherwise crash the whole process (and release port 4727).
process.on('unhandledRejection', (e) => log('unhandledRejection: ' + ((e && e.message) || e)));
process.on('uncaughtException', (e) => log('uncaughtException: ' + ((e && e.message) || e)));
process.on('SIGTERM', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));

// The deliberate exception to the never-die policy above: die with the app.
//
// Windows delivers no signal to a child when its parent dies, and the handlers above actively
// swallow the EPIPE that a broken stdout would otherwise raise — so this process is immortal. That
// is correct while the app lives and fatal once it doesn't: a crash, a Task Manager End Task, or a
// power-loss reboot leaves it holding :4727 forever, and the next launch cannot start a farmer.
//
// stdin's write end is held ONLY by the Electron main process (Playwright's Chromium is a
// grandchild and never inherits it), so its EOF is an exact parent-death signal. Chosen over
// polling process.kill(ppid, 0) because that is defeated by PID reuse.
//
// Gated on the env var the app sets, so a hand-launched standalone broker is unaffected.
if (process.env.ZYN_PARENT_WATCH === '1') {
  process.stdin.resume();
  const bye = () => process.exit(0);
  process.stdin.on('end', bye);
  process.stdin.on('close', bye);
  process.stdin.on('error', bye);
}
